apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  namespace: fenqi-codis
  labels:
      name: zookeeper-1
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: followers
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
  type: NodePort
  selector:
    name: zookeeper
    server-id: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  namespace: fenqi-codis
  labels:
      name: zookeeper-2
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: followers
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
  type: NodePort
  selector:
    name: zookeeper
    server-id: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  namespace: fenqi-codis
  labels:
      name: zookeeper-3
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: followers
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
  type: NodePort
  selector:
    name: zookeeper
    server-id: "3"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-1
  namespace: fenqi-codis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
        server-id: "1"
    spec:
      volumes:
        - hostPath:
            path: /tmp/zookeeper/data1
          name: data
        - hostPath:
            path: /tmp/zookeeper/log1
          name: log
      containers:
        - name: server
          image: hub.c.163.com/dwyane/zookeeper:3.4.5-cdh5.7.0
          env:
            - name: SERVER_ID
              value: "1"
            - name: MAX_SERVERS
              value: "3"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /opt/zookeeper/data
              name: data
            - mountPath: /opt/zookeeper/log
              name: log
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-2
  namespace: fenqi-codis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
        server-id: "2"
    spec:
      volumes:
        - hostPath:
            path: /tmp/zookeeper/data2
          name: data
        - hostPath:
            path: /tmp/zookeeper/log2
          name: log
      containers:
        - name: server
          image: hub.c.163.com/dwyane/zookeeper:3.4.5-cdh5.7.0
          env:
            - name: SERVER_ID
              value: "2"
            - name: MAX_SERVERS
              value: "3"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /opt/zookeeper/data
              name: data
            - mountPath: /opt/zookeeper/log
              name: log
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-3
  namespace: fenqi-codis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
        server-id: "3"
    spec:
      volumes:
        - hostPath:
            path: /tmp/zookeeper/data3
          name: data
        - hostPath:
            path: /tmp/zookeeper/log3
          name: log
      containers:
        - name: server
          image: hub.c.163.com/dwyane/zookeeper:3.4.5-cdh5.7.0
          env:
            - name: SERVER_ID
              value: "3"
            - name: MAX_SERVERS
              value: "3"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /opt/zookeeper/data
              name: data
            - mountPath: /opt/zookeeper/log
              name: log
