apiVersion: v1
kind: Service
metadata:
  name: codis-dashboard
  namespace: fenqi-codis
spec:
  ports:
    - name: dashboard
      port: 18087
      targetPort: 18087
  type: NodePort
  selector:
      name: codis-dashboard
      product: "test"
---
apiVersion: v1
kind: Service
metadata:
  name: codis-server
  namespace: fenqi-codis 
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: NodePort
  selector:
    name: codis-server
    group: "1"
    product: "test"
---
apiVersion: v1
kind: Service
metadata:
  name: codis-proxy
  namespace: fenqi-codis 
spec:
  ports:
    - name: proxy 
      port: 19000
      targetPort: 19000
    - name: http
      port: 11000
      targetPort: 11000
  type: NodePort
  selector:
    name: codis-proxy
    product: "test"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-dashboard
  namespace: fenqi-codis 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: codis-dashboard
        product: "test"
    spec:
      containers:
        - name: dashboard
          image: hub.c.163.com/dwyane/codis-dashboard:2.0
          ports:
            - containerPort: 18087
          env:
            - name: ZK_URL
              value: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
            - name: PRODUCT_NAME
              value: "test"
            - name: DASHBOARD_IP
              value: "127.0.0.1"
            - name: PROXY_ID
              value: ""
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-server
  namespace: fenqi-codis 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: codis-server
        product: "test"
    spec:
      containers:
        - name: codis-server
          env:
            - name: IS_SLAVE_REDIS
              value: "False"
            - name: REDIS_MAXMEMORY
              value: "1g"
          image: hub.c.163.com/dwyane/codis-server:2.0
          ports:
             - containerPort: 6379
               name: redis 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-proxy
  namespace: fenqi-codis 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: codis-proxy
        product: "test"
    spec:
      containers:
        - name: codis-proxy
          env:
            - name: ZK_URL
              value: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
            - name: PRODUCT_NAME
              value: "test"
            - name: DASHBOARD_IP
              value: "codis-dashboard"
            - name: PROXY_ID
              value: "proxy-1"
          image: hub.c.163.com/dwyane/codis-proxy:2.0
          ports:
             - containerPort: 19000
               name: proxy
             - containerPort: 11000
               name: http
